source 'https://github.com/CocoaPods/Specs.git'

target 'ParentalGate', :exclusive => true do
  pod "ParentalGate", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ParentalGate", :path => "../"

  
end
